### ISSUE TITLE
Quest reward hints missing

### ISSUE THREAD

**Issue by redrhetoric** [mopioid/Borderlands-Loot-Randomizer#10]
every quest i've come across shows as having no reward and 0 xp, though still shows money
quest rewards are still there, only the hints are missing
has been tried on multiple seeds, but has definitely happened on agt3f-ba2ao-p77ri default settings
no mods beside the loot randomizer are active

**Comment by mopioid** [comment]
This is the intended behavior!

Side quests do not award XP until UVHM, as farming them would leave the player grossly overleveled, especially when combined with the amount of content already engaged with.

No reward preview is provided as that would spoil the reward without the mission even having been done; compare it to enemies, where you need to kill them at least once to see their hint or loot.
