### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by xb0x1sg4y** [mopioid/Borderlands-Loot-Randomizer#15]
i load borderlands and open the console and there is an import error saying it cannot import name 'ModMenu' from 'Mods' with the init.py

**Comment by mopioid** [comment]
This is not an issue with Loot Randomizer, but rather you have not installed it or the SDK correctly. Please adhere carefully to the instructions: https://github.com/mopioid/Borderlands-Loot-Randomizer/wiki/Installation
