### ISSUE TITLE
Not getting quest specific items

### ISSUE THREAD

**Issue by Shadow4077** [mopioid/Borderlands-Loot-Randomizer#2]
I generated a new seed with the new loot tracking update and I went to Marcus shortly after I got to Sanctuary. When doing the "Rock, Paper Genoside: Fire Weapons!" I noticed that I didn't get a fire pistol like normal. Luckily I had a fire weapon already and ended up farming Marcus and the gun machine for a shock weapon.

I had to end up going back to the previous release to end up being able to play the loot randomizer.

**Comment by mopioid** [comment]
That was a deliberate change in the version 1.1 update... Feel free to stay on an old version if you find the Marcus missions too difficult, but I don't recommend it because of all the other buffs and features. You might even find the Marcus missions are more fun this way!
