### ISSUE TITLE
I got "Did It All" achievement from finishing the first few missions

### ISSUE THREAD

**Issue by 10pointstogryffindor** [mopioid/Borderlands-Loot-Randomizer#3]
I did "This Town Ain't Big Enough" mission and got the "Did It All" achievement, which is an achievement you get from doing all the side missions. I know this isn't right because there is a handful of side missions I haven't even touched yet. This doesn't bother me but I thought you should know since this does seem like a bug. Below is a screenshot that shows "Did It All" being completed but "Went Five Rounds" is not (every Circle of Slaughter Round 5 mission is needed to achieve Did It All, I have none completed). Anyway thanks for this awesome mod!

![0414_003](https://github.com/mopioid/Borderlands-Loot-Randomizer/assets/105363017/02e7341d-5c38-405c-b95a-0f03e01808a0)

**Comment by mopioid** [comment]
Oh dear, you confirm that you are on version 1.1 or later? This is supposed to be fixed.

In any case, apologies for the inconvenience... I recommend Steam Achievement Manager if you want to undo it: https://github.com/gibbed/SteamAchievementManager/releases/tag/7.0.25
