### ISSUE TITLE
Missions are not giving any rewards

### ISSUE THREAD

**Issue by PengWeng01** [mopioid/Borderlands-Loot-Randomizer#4]
I wanted to play the Mod but noticed during the Mission "Bad Hair Day" that i wouldnt recieve any reward for it i tried other missions too. But none of them would give me item rewards.

**Comment by PengWeng01** [comment]
Missions also are not giving me any XP

**Comment by mopioid** [comment]
- Enemies are dropping items/hints, but not missions?
- What seed are you running?
- What does your console show after turning in a mission?

Side missions not giving XP in normal or TVHM is an intended feature.

**Comment by PengWeng01** [comment]
1. Yes Enemies are dropping item/hints and missions give me nothing.
2. My Seed is xc22a-xak77-777ra
3. Im not sure how to see my console output in game since im fairly new to this

Ok thats good to know, but i still should get items from quests right?

**Comment by PengWeng01** [comment]
I just did a mission and when i picked it up it showed me that i wont recieve any rewards and it told me that i got nothing when i turned it it just the empty frame with quest completed. Quest was Positive Self Image. I dont know if thats important but i also run a mod that lets me reroll items for Eridium could that be a problem?

**Comment by mopioid** [comment]
Yep, disable Reward Reroller and try again.

**Comment by PengWeng01** [comment]
Worked like a charm. Thank u so much. And im sorry that i didnt try that before i bothered u. have a great one.

**Comment by mopioid** [comment]
Not at all, have fun!
