### ISSUE TITLE
Bosses stop dropping "hint" Echos

### ISSUE THREAD

**Issue by mleslie2593** [mopioid/Borderlands-Loot-Randomizer#5]
Sometimes when I'm farming bosses, they stop dropping their Echo devices. Exiting the game seems to fix it temporarily. Are the Echos meant to be a guaranteed drop?

**Comment by mopioid** [comment]
The mandatory 5 second tutorial explained that when you interact with a hint, it "dismisses" that hint, and also you can reset your dismissed hints from the mod's options. ;)

**Comment by mleslie2593** [comment]
Word! Thanks!
