### ISSUE TITLE
Loot midgets

### ISSUE THREAD

**Issue by SmithyfromSing** [mopioid/Borderlands-Loot-Randomizer#6]
This is a damn good mod. 

One thing I have noticed is that loot midgets that have spawned out of containers are dropping just ammo. Three of us are playing various characters, at different levels, but nothing has dropped so far. I think collectively its nearly nearly 20 or so,

Is there somewhere I should look in the seed options/generator that may impact this?

I have checked my own mods that I have on, BL2fix and a couple of minor ones, but nothing related to loot or drop rates,

**Comment by mopioid** [comment]
Really glad you like it!

Normal Loot Midgets are classified as "very rare enemy," while Space Cowboy and Doctor's Orders Midgets are classified as "mission enemies":

https://github.com/mopioid/Borderlands-Loot-Randomizer/wiki/Locations

If you want to review the options you selected for your seed, you can via the tracker (Options > Mods > Loot Randomizer > Open Seed Tracker).

**Comment by SmithyfromSing** [comment]
> Really glad you like it!
> 
> Normal Loot Midgets are classified as "very rare enemy," while Space Cowboy and Doctor's Orders Midgets are classified as "mission enemies":
> 
> https://github.com/mopioid/Borderlands-Loot-Randomizer/wiki/Locations
> 
> If you want to review the options you selected for your seed, you can via the tracker (Options > Mods > Loot Randomizer > Open Seed Tracker).

Thanks mate.
