### ISSUE TITLE
Crashes in multiplayer and unable to interact with some NPCs

### ISSUE THREAD

**Issue by Quiggli** [mopioid/Borderlands-Loot-Randomizer#8]
When the randomizer is activated in multiplayer, the game occasionally crashes while loading in Overlook Bar, Sawtooth Cauldron, Flamerock Refuge, and The Highlands. Have only tried with one seed. Error that pops up is attached. Aside from that, unable to interact with Murderlin, no action prompt appears when coming up to him.

![BL2 Randomizer crash log](https://github.com/mopioid/Borderlands-Loot-Randomizer/assets/172183239/0232f387-9609-4dbb-b014-26782197e602)

**Comment by mopioid** [comment]
Apologies for the long late reply - these client crashes should be entirely fixed in version 1.2 (they were actually all the result of the same culprit function).
