### ISSUE TITLE
Just doesn't work at all.

### ISSUE THREAD

**Issue by Innomen** [mopioid/Borderlands-Loot-Randomizer#9]
Epic, windows 11, sdk installed, mod enabled, rewards are not randomized or dropping at all? knuckledragger gave nothing? Went all the way to boom boom, nothing different.

**Comment by mystic8701** [comment]
same did u find a fix?

**Comment by Innomen** [comment]
> same did u find a fix?

I did not, but tbf I did also basically give up.

**Comment by mopioid** [comment]
https://github.com/mopioid/Borderlands-Loot-Randomizer#getting-started
